name: lsa
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=2.2.1=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.5=pyhd8ed1ab_0
  - ca-certificates=2023.5.7=hbcca054_0
  - debugpy=1.5.1=py38h295c915_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - ipykernel=6.15.0=pyh210e3f2_0
  - ipython=8.12.0=pyh41d4057_0
  - jedi=0.18.2=pyhd8ed1ab_0
  - jupyter_client=7.0.6=pyhd8ed1ab_0
  - jupyter_core=4.12.0=py38h578d9bd_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - openssl=3.0.9=h7f8727e_0
  - packaging=23.1=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pip=23.1.2=py38h06a4308_0
  - prompt-toolkit=3.0.39=pyha770c72_0
  - prompt_toolkit=3.0.39=hd8ed1ab_0
  - psutil=5.9.0=py38h5eee18b_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pygments=2.15.1=pyhd8ed1ab_0
  - python=3.8.17=h955ad1f_0
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.8=2_cp38
  - pyzmq=19.0.2=py38ha71036d_2
  - readline=8.2=h5eee18b_0
  - setuptools=67.8.0=py38h06a4308_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.41.2=h5eee18b_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tk=8.6.12=h1ccaba5_0
  - tornado=6.1=py38h0a891b7_3
  - traitlets=5.9.0=pyhd8ed1ab_0
  - typing_extensions=4.7.1=pyha770c72_0
  - wcwidth=0.2.6=pyhd8ed1ab_0
  - wheel=0.38.4=py38h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - zeromq=4.3.4=h9c3ff4c_1
  - zlib=1.2.13=h5eee18b_0
  - pip:
    - addict==2.4.0
    - aiofiles==23.1.0
    - aiohttp==3.8.4
    - aiosignal==1.3.1
    - altair==5.0.1
    - anyio==3.7.1
    - arrow==1.2.3
    - async-timeout==4.0.2
    - attrs==23.1.0
    - backoff==2.2.1
    - beautifulsoup4==4.12.2
    - blessed==1.20.0
    - certifi==2023.5.7
    - charset-normalizer==3.2.0
    - click==8.1.4
    - cmake==3.26.4
    - contourpy==1.1.0
    - croniter==1.4.1
    - cycler==0.11.0
    - dateutils==0.6.12
    - deepdiff==6.3.1
    - exceptiongroup==1.1.2
    - fastapi==0.100.0
    - ffmpy==0.3.0
    - filelock==3.12.2
    - fonttools==4.41.0
    - frozenlist==1.4.0
    - fsspec==2023.6.0
    - gradio==3.32.0
    - gradio-client==0.2.9
    - groundingdino==0.1.0
    - h11==0.14.0
    - httpcore==0.17.3
    - httpx==0.24.1
    - huggingface-hub==0.13.4
    - idna==3.4
    - importlib-metadata==6.8.0
    - importlib-resources==6.0.0
    - inquirer==3.1.3
    - itsdangerous==2.1.2
    - jinja2==3.1.2
    - jsonschema==4.18.2
    - jsonschema-specifications==2023.6.1
    - kiwisolver==1.4.4
    - lang-sam==0.1.0
    - lightning==2.0.5
    - lightning-cloud==0.5.37
    - lightning-utilities==0.9.0
    - linkify-it-py==2.0.2
    - lit==16.0.6
    - markdown-it-py==2.2.0
    - markupsafe==2.1.3
    - matplotlib==3.7.2
    - mdit-py-plugins==0.3.3
    - mdurl==0.1.2
    - mpmath==1.3.0
    - multidict==6.0.4
    - networkx==3.1
    - numpy==1.24.4
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cuda-cupti-cu11==11.7.101
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cudnn-cu11==8.5.0.96
    - nvidia-cufft-cu11==10.9.0.58
    - nvidia-curand-cu11==10.2.10.91
    - nvidia-cusolver-cu11==11.4.0.1
    - nvidia-cusparse-cu11==11.7.4.91
    - nvidia-nccl-cu11==2.14.3
    - nvidia-nvtx-cu11==11.7.91
    - opencv-python==4.8.0.74
    - ordered-set==4.1.0
    - orjson==3.9.2
    - pandas==2.0.3
    - pillow==9.3.0
    - pkgutil-resolve-name==1.3.10
    - platformdirs==3.8.1
    - pycocotools==2.0.6
    - pydantic==1.10.11
    - pydub==0.25.1
    - pyjwt==2.7.0
    - pyparsing==3.0.9
    - python-editor==1.0.4
    - python-multipart==0.0.6
    - pytorch-lightning==2.0.5
    - pytz==2023.3
    - pyyaml==6.0
    - readchar==4.0.5
    - referencing==0.29.1
    - regex==2023.6.3
    - requests==2.31.0
    - rich==13.4.2
    - rpds-py==0.8.10
    - safetensors==0.3.1
    - segment-anything==1.0
    - semantic-version==2.10.0
    - sniffio==1.3.0
    - soupsieve==2.4.1
    - spectral==0.23.1
    - starlette==0.27.0
    - starsessions==1.3.0
    - supervision==0.6.0
    - sympy==1.12
    - timm==0.9.2
    - tokenizers==0.13.3
    - tomli==2.0.1
    - toolz==0.12.0
    - torch==2.0.1
    - torchmetrics==1.0.0
    - torchvision==0.15.2
    - tqdm==4.65.0
    - transformers==4.29.0
    - triton==2.0.0
    - tzdata==2023.3
    - uc-micro-py==1.0.2
    - urllib3==2.0.3
    - uvicorn==0.22.0
    - websocket-client==1.6.1
    - websockets==11.0.3
    - yapf==0.40.1
    - yarl==1.9.2
    - zipp==3.16.1
prefix: /home/paperspace/anaconda3/envs/lsa
