name: lsa
channels:
  - pytorch
  - rapidsai
  - nvidia
  - nodefaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - aom=3.9.1=hac33072_0
  - blas=2.116=mkl
  - blas-devel=3.9.0=16_linux64_mkl
  - brotli-python=1.1.0=py39h3d6467e_1
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2024.7.4=hbcca054_0
  - cairo=1.18.0=hebfffa5_3
  - certifi=2024.7.4=pyhd8ed1ab_0
  - cffi=1.17.0=py39h49a4b6b_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.6.37=0
  - cuda-runtime=12.1.0=0
  - cuda-version=12.6=3
  - dav1d=1.2.1=hd590300_0
  - expat=2.6.2=h59595ed_0
  - ffmpeg=7.0.2=gpl_h226ea3b_102
  - filelock=3.15.4=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_2
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.12.1=h267a509_2
  - fribidi=1.0.10=h36c2ea0_0
  - gettext=0.22.5=he02047a_3
  - gettext-tools=0.22.5=he02047a_3
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.1.5=py39h048c657_1
  - gnutls=3.8.7=h32866dd_0
  - graphite2=1.3.13=h59595ed_1003
  - h2=4.1.0=pyhd8ed1ab_0
  - harfbuzz=9.0.0=hda332d3_1
  - hpack=4.0.0=pyh9f0ad1d_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.8=pyhd8ed1ab_0
  - jinja2=3.1.4=pyhd8ed1ab_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.16=hb7c19ff_0
  - ld_impl_linux-64=2.40=hf3520f5_7
  - lerc=4.0.0=h27087fc_0
  - libabseil=20240116.2=cxx17_he02047a_1
  - libasprintf=0.22.5=he8f35ee_3
  - libasprintf-devel=0.22.5=he8f35ee_3
  - libass=0.17.3=h1dc1e6a_0
  - libblas=3.9.0=16_linux64_mkl
  - libcblas=3.9.0=16_linux64_mkl
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.11.0.15=0
  - libcurand=10.3.7.37=0
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libdeflate=1.21=h4bc722e_0
  - libdrm=2.4.123=hb9d3cd8_0
  - libexpat=2.6.2=h59595ed_0
  - libffi=3.4.2=h7f98852_5
  - libgcc=14.1.0=h77fa898_1
  - libgcc-ng=14.1.0=h69a702a_1
  - libgettextpo=0.22.5=he02047a_3
  - libgettextpo-devel=0.22.5=he02047a_3
  - libgfortran=14.1.0=h69a702a_1
  - libgfortran-ng=14.1.0=h69a702a_1
  - libgfortran5=14.1.0=hc5f4f2c_1
  - libglib=2.80.3=h315aac3_2
  - libgomp=14.1.0=h77fa898_1
  - libhwloc=2.11.1=default_hecaa2ac_1000
  - libiconv=1.17=hd590300_2
  - libidn2=2.3.7=hd590300_0
  - libjpeg-turbo=3.0.0=hd590300_1
  - liblapack=3.9.0=16_linux64_mkl
  - liblapacke=3.9.0=16_linux64_mkl
  - libnpp=12.0.2.50=0
  - libnsl=2.0.1=hd590300_0
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libopenvino=2024.3.0=h2da1b83_0
  - libopenvino-auto-batch-plugin=2024.3.0=hb045406_0
  - libopenvino-auto-plugin=2024.3.0=hb045406_0
  - libopenvino-hetero-plugin=2024.3.0=h5c03a75_0
  - libopenvino-intel-cpu-plugin=2024.3.0=h2da1b83_0
  - libopenvino-intel-gpu-plugin=2024.3.0=h2da1b83_0
  - libopenvino-intel-npu-plugin=2024.3.0=h2da1b83_0
  - libopenvino-ir-frontend=2024.3.0=h5c03a75_0
  - libopenvino-onnx-frontend=2024.3.0=h07e8aee_0
  - libopenvino-paddle-frontend=2024.3.0=h07e8aee_0
  - libopenvino-pytorch-frontend=2024.3.0=he02047a_0
  - libopenvino-tensorflow-frontend=2024.3.0=h39126c6_0
  - libopenvino-tensorflow-lite-frontend=2024.3.0=he02047a_0
  - libopus=1.3.1=h7f98852_1
  - libpciaccess=0.18=hd590300_0
  - libpng=1.6.43=h2797004_0
  - libprotobuf=4.25.3=h08a7969_0
  - libsqlite=3.46.0=hde9e2c9_0
  - libstdcxx=14.1.0=hc0a3c3a_1
  - libstdcxx-ng=14.1.0=h4852527_1
  - libtasn1=4.19.0=h166bdaf_0
  - libtiff=4.6.0=h46a8edc_4
  - libunistring=0.9.10=h7f98852_0
  - libuuid=2.38.1=h0b41bf4_0
  - libva=2.22.0=hb711507_0
  - libvpx=1.14.1=hac33072_0
  - libwebp-base=1.4.0=hd590300_0
  - libxcb=1.16=hb9d3cd8_1
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.12.7=he7c6b58_4
  - libzlib=1.3.1=h4ab18f5_1
  - llvm-openmp=15.0.7=h0cdce71_0
  - markupsafe=2.1.5=py39hd1e30aa_0
  - mkl=2022.1.0=h84fe81f_915
  - mkl-devel=2022.1.0=ha770c72_916
  - mkl-include=2022.1.0=h84fe81f_915
  - mpc=1.3.1=h24ddda3_0
  - mpfr=4.2.1=h38ae2d0_2
  - mpmath=1.3.0=pyhd8ed1ab_0
  - ncurses=6.5=he02047a_1
  - nettle=3.9.1=h7ab15ed_0
  - networkx=3.2.1=pyhd8ed1ab_0
  - ocl-icd=2.3.2=hd590300_1
  - openh264=2.4.1=h59595ed_0
  - openjpeg=2.5.2=h488ebb8_0
  - openssl=3.3.1=hb9d3cd8_3
  - p11-kit=0.24.1=hc5aa10d_0
  - pcre2=10.44=hba22ea6_2
  - pip=24.2=pyhd8ed1ab_0
  - pixman=0.43.2=h59595ed_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - pugixml=1.14=h59595ed_0
  - pycparser=2.22=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.9.19=h0755675_0_cpython
  - python_abi=3.9=5_cp39
  - pytorch=2.4.0=py3.9_cuda12.1_cudnn9.1.0_0
  - pytorch-cuda=12.1=ha16c6d3_5
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.2=py39hcd6043d_0
  - readline=8.2=h8228510_1
  - requests=2.32.3=pyhd8ed1ab_0
  - setuptools=72.2.0=pyhd8ed1ab_0
  - snappy=1.2.1=ha2e4443_0
  - svt-av1=2.2.1=h5888daf_0
  - sympy=1.13.2=pypyh2585a3b_103
  - tbb=2021.12.0=h434a139_3
  - tk=8.6.13=noxft_h4845f30_101
  - torchtriton=3.0.0=py39
  - torchvision=0.19.0=py39_cu121
  - typing_extensions=4.12.2=pyha770c72_0
  - urllib3=2.2.2=pyhd8ed1ab_1
  - wayland=1.23.1=h3e06ad9_0
  - wayland-protocols=1.36=hd8ed1ab_0
  - wheel=0.44.0=pyhd8ed1ab_0
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xorg-fixesproto=5.0=h7f98852_1002
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.1.1=hd590300_0
  - xorg-libsm=1.2.4=h7391055_0
  - xorg-libx11=1.8.9=hb711507_1
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - zlib=1.3.1=h4ab18f5_1
  - zstandard=0.23.0=py39h623c9ba_0
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - addict==2.4.0
      - aiofiles==23.2.1
      - aiohappyeyeballs==2.4.0
      - aiohttp==3.10.5
      - aiosignal==1.3.1
      - altair==5.4.1
      - annotated-types==0.7.0
      - anyio==4.4.0
      - async-timeout==4.0.3
      - attrs==24.2.0
      - click==8.1.7
      - contourpy==1.3.0
      - cycler==0.12.1
      - defusedxml==0.7.1
      - exceptiongroup==1.2.2
      - fastapi==0.112.2
      - ffmpy==0.4.0
      - fonttools==4.53.1
      - frozenlist==1.4.1
      - fsspec==2024.6.1
      - gradio==3.50.2
      - gradio-client==0.6.1
      - groundingdino==0.1.0
      - h11==0.14.0
      - httpcore==1.0.5
      - httpx==0.27.2
      - huggingface-hub==0.23.5
      - importlib-metadata==8.4.0
      - importlib-resources==6.4.4
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - kiwisolver==1.4.5
      - lang-sam==0.1.0
      - lightning==2.4.0
      - lightning-utilities==0.11.6
      - matplotlib==3.9.2
      - multidict==6.0.5
      - narwhals==1.5.5
      - numpy==1.26.4
      - opencv-python==4.10.0.84
      - opencv-python-headless==4.10.0.84
      - orjson==3.10.7
      - packaging==24.1
      - pandas==2.2.2
      - pillow==9.4.0
      - platformdirs==4.2.2
      - pycocotools==2.0.8
      - pydantic==2.8.2
      - pydantic-core==2.20.1
      - pydub==0.25.1
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - python-multipart==0.0.9
      - pytorch-lightning==2.4.0
      - pytz==2024.1
      - referencing==0.35.1
      - regex==2024.7.24
      - rpds-py==0.20.0
      - safetensors==0.4.4
      - scipy==1.13.1
      - segment-anything==1.0
      - semantic-version==2.10.0
      - six==1.16.0
      - sniffio==1.3.1
      - starlette==0.38.2
      - supervision==0.22.0
      - timm==1.0.9
      - tokenizers==0.19.1
      - tomli==2.0.1
      - torchmetrics==1.4.1
      - tqdm==4.66.5
      - transformers==4.44.2
      - tzdata==2024.1
      - uvicorn==0.30.6
      - websockets==11.0.3
      - yapf==0.40.2
      - yarl==1.9.4
      - zipp==3.20.1
